name: Test Student Support Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start backend
        run: |
          nohup npm start > server.log 2>&1 &
          sleep 12

      # ------------------- Keyword FAQ Tests -------------------
      - name: Test FAQ - Hostel Mess
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"When is mess food served?","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "Hostel mess timings"

      - name: Test FAQ - Sports Ground
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Where is cricket ground?","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "Sports ground"

      - name: Test FAQ - WiFi
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"How to connect wifi?","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "WiFi login"

      - name: Test FAQ - Fees
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Check my fees","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "pending fees"

      - name: Test FAQ - Dues
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Do I have any dues?","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "dues pending"

      - name: Test FAQ - Scholarship
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Scholarship details","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "scholarship portal"

      - name: Test FAQ - Deadline
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"When is the next deadline?","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "deadline"

      - name: Test FAQ - Books
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Where can I buy books?","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "books"

      - name: Test FAQ - Laptop
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Where to get laptop?","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "laptop"

      - name: Test FAQ - Mentor AI
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"AI mentor available?","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "Artificial Intelligence"

      - name: Test FAQ - Counseling
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"I want counseling","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "Counseling services"

      - name: Test FAQ - Exam
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Exam schedule","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "Exam schedules"

      - name: Test FAQ - Revaluation
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"How to apply for revaluation?","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "Revaluation"

      - name: Test FAQ - Passing Marks
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"What are passing marks?","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "Passing marks"

      - name: Test FAQ - Clinic
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Where is clinic?","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "clinic"

      - name: Test FAQ - Mental Health
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"I feel depressed","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "helpline"

      - name: Test FAQ - Events
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Upcoming fest","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "events"

      - name: Test FAQ - Sports Club
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"How to join football club?","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "sports office"

      - name: Test FAQ - Bonafide
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Need bonafide certificate","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "bonafide"

      - name: Test FAQ - ID Card
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Lost my ID card","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "ID card"

      - name: Test FAQ - Admin Timing
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"When is admin office open?","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "Admin block"

      - name: Test FAQ - Library Borrow
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"How many books can I borrow?","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "issue up to 3 books"

      - name: Test FAQ - Library Fine
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"library fine","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "Library fine"

      - name: Test FAQ - Bus
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Is there a bus service?","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "buses"

      - name: Test FAQ - Bus Pass
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"How to get bus pass?","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "bus pass"

      - name: Test FAQ - Contact Admin
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"How to contact admin?","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "Contact admin office"

      # ------------------- Intent Tests -------------------
      - name: Test FinanceIntent - Valid
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Check finance for STU001","intent":{"displayName":"FinanceIntent"},"parameters":{"studentId":"STU001"}}}')
          echo "$RESPONSE" | grep "Finance Summary"

      - name: Test ParentStatusIntent
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Parent dashboard","intent":{"displayName":"ParentStatusIntent"},"parameters":{"parentId":"PARENT001"}}}')
          echo "$RESPONSE" | grep "Parent Dashboard"

      - name: Test MentorStatusIntent
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Mentor dashboard","intent":{"displayName":"MentorStatusIntent"},"parameters":{"mentorId":"MENTOR001"}}}')
          echo "$RESPONSE" | grep "Mentor Dashboard"

      - name: Test CounselingIntent
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"I need counseling","intent":{"displayName":"CounselingIntent"}}}')
          echo "$RESPONSE" | grep "Counseling services"

      - name: Test DistressIntent
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"I feel very depressed","intent":{"displayName":"DistressIntent"}}}')
          echo "$RESPONSE" | grep "distress"

      - name: Test MarketplaceIntent
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Show marketplace","intent":{"displayName":"MarketplaceIntent"}}}')
          echo "$RESPONSE" | grep "Marketplace Listings"

      - name: Test MentorshipIntent
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Show mentors","intent":{"displayName":"MentorshipIntent"}}}')
          echo "$RESPONSE" | grep "Mentorship Available"

      # ------------------- Sentiment -------------------
      - name: Test Sentiment - Positive
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"I am very happy today","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "Glad you’re doing well"

      - name: Test Sentiment - Negative
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"I am hopeless","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "counselor"

      # ------------------- Fallback -------------------
      - name: Test Fallback - Unknown Query
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Blah blah blah","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "couldn’t find"
