name: Test Student Support Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start backend
        run: |
          nohup npm start > server.log 2>&1 &
          sleep 12

      # ---------- Keyword FAQs (from Sheets) ----------
      - name: Test FAQ - Hostel Mess
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"When is mess food served?","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "Hostel mess timings"

      - name: Test FAQ - Sports Ground
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -d '{"queryResult":{"queryText":"Where is cricket ground?","intent":{"displayName":"Default Fallback Intent"}}}' \
            -H "Content-Type: application/json")
          echo "$RESPONSE" | grep "Sports ground"

      - name: Test FAQ - WiFi
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -d '{"queryResult":{"queryText":"How to connect wifi?","intent":{"displayName":"Default Fallback Intent"}}}' \
            -H "Content-Type: application/json")
          echo "$RESPONSE" | grep "WiFi login"

      - name: Test FAQ - Fees
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -d '{"queryResult":{"queryText":"Check my fees","intent":{"displayName":"Default Fallback Intent"}}}' \
            -H "Content-Type: application/json")
          echo "$RESPONSE" | grep "pending fees"

      - name: Test FAQ - Deadlines
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -d '{"queryResult":{"queryText":"What is the next deadline?","intent":{"displayName":"Default Fallback Intent"}}}' \
            -H "Content-Type: application/json")
          echo "$RESPONSE" | grep "deadline"

      - name: Test FAQ - Library Fine
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -d '{"queryResult":{"queryText":"library fine details","intent":{"displayName":"Default Fallback Intent"}}}' \
            -H "Content-Type: application/json")
          echo "$RESPONSE" | grep "Library fine"

      - name: Test FAQ - Counseling
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -d '{"queryResult":{"queryText":"I want counseling","intent":{"displayName":"Default Fallback Intent"}}}' \
            -H "Content-Type: application/json")
          echo "$RESPONSE" | grep "Counseling services"

      - name: Test FAQ - Bus Pass
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -d '{"queryResult":{"queryText":"How to get bus pass?","intent":{"displayName":"Default Fallback Intent"}}}' \
            -H "Content-Type: application/json")
          echo "$RESPONSE" | grep "bus pass"

      - name: Test FAQ - Contact Admin
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -d '{"queryResult":{"queryText":"How to contact admin?","intent":{"displayName":"Default Fallback Intent"}}}' \
            -H "Content-Type: application/json")
          echo "$RESPONSE" | grep "Contact admin office"

      # (💡 Repeat for all 40+ keywords from sheet — hostel, sports, wifi, fees, dues, scholarships, deadlines, books, laptop, mentorship, revaluation, clinic, events, sports club, bonafide, ID card, admin timing, library borrow, transport, etc.)

      # ---------- Intents ----------
      - name: Test FinanceIntent - Valid
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Check finance for STU001","intent":{"displayName":"FinanceIntent"},"parameters":{"studentId":"STU001"}}}')
          echo "$RESPONSE" | grep "Finance Summary"

      - name: Test FinanceIntent - Missing ID
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Show my finance details","intent":{"displayName":"FinanceIntent"},"parameters":{}}}')
          echo "$RESPONSE" | grep "Please provide"

      - name: Test ParentStatusIntent
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Parent dashboard","intent":{"displayName":"ParentStatusIntent"},"parameters":{"parentId":"PARENT001"}}}')
          echo "$RESPONSE" | grep "Parent Dashboard"

      - name: Test MentorStatusIntent
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Mentor dashboard","intent":{"displayName":"MentorStatusIntent"},"parameters":{"mentorId":"MENTOR001"}}}')
          echo "$RESPONSE" | grep "Mentor Dashboard"

      - name: Test CounselingIntent
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"I need counseling","intent":{"displayName":"CounselingIntent"}}}')
          echo "$RESPONSE" | grep "Counseling services"

      - name: Test DistressIntent
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"I feel very depressed","intent":{"displayName":"DistressIntent"}}}')
          echo "$RESPONSE" | grep "distress"

      - name: Test MarketplaceIntent
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Show marketplace","intent":{"displayName":"MarketplaceIntent"}}}')
          echo "$RESPONSE" | grep "Marketplace Listings"

      - name: Test MentorshipIntent
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Show mentors","intent":{"displayName":"MentorshipIntent"}}}')
          echo "$RESPONSE" | grep "Mentorship Available"

      # ---------- Sentiment ----------
      - name: Test Sentiment - Positive
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"I am very happy today","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "Glad you’re doing well"

      - name: Test Sentiment - Negative
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"I am hopeless","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "connect you to a counselor"

      # ---------- Fallback ----------
      - name: Test Fallback - Unknown Query
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Blah blah blah","intent":{"displayName":"Default Fallback Intent"}}}')
          echo "$RESPONSE" | grep "couldn’t find"
