name: Backend Tests

on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual run

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Start backend
      - name: Start backend
        run: |
          nohup npm start > server.log 2>&1 &
          sleep 12

      # 5. Run tests
      - name: Run Keyword FAQ Tests
        run: |
          # Hostel Mess
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"When is mess food served?","intent":{"displayName":"Default Fallback Intent"}}}' \
            | grep "Hostel mess timings"

          # Sports Ground
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Where is cricket ground?","intent":{"displayName":"Default Fallback Intent"}}}' \
            | grep "Sports ground"

          # WiFi
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"How to connect wifi?","intent":{"displayName":"Default Fallback Intent"}}}' \
            | grep "WiFi login"

          # Fees
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Check my fees","intent":{"displayName":"Default Fallback Intent"}}}' \
            | grep "fees"

          # Dues
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Do I have any dues?","intent":{"displayName":"Default Fallback Intent"}}}' \
            | grep "dues"

          # Scholarship
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Are there scholarships available?","intent":{"displayName":"Default Fallback Intent"}}}' \
            | grep "scholarship"

          # Deadlines
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"What is the next deadline?","intent":{"displayName":"Default Fallback Intent"}}}' \
            | grep "deadline"

          # Books
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Where can I buy books?","intent":{"displayName":"Default Fallback Intent"}}}' \
            | grep "books"

          # Laptop
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Where can I buy a laptop?","intent":{"displayName":"Default Fallback Intent"}}}' \
            | grep "laptop"

          # Counseling
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"I want counseling","intent":{"displayName":"Default Fallback Intent"}}}' \
            | grep "Counseling"

          # Bus Pass
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"How to get bus pass?","intent":{"displayName":"Default Fallback Intent"}}}' \
            | grep "bus pass"

          # Contact Admin
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"How to contact admin?","intent":{"displayName":"Default Fallback Intent"}}}' \
            | grep "Contact admin"

      - name: Run Intent Tests
        run: |
          # Finance Intent
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Check finance for STU001","intent":{"displayName":"FinanceIntent"},"parameters":{"studentId":"STU001"}}}' \
            | grep "Finance Summary"

          # Parent Status
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Parent dashboard","intent":{"displayName":"ParentStatusIntent"},"parameters":{"parentId":"PARENT001"}}}' \
            | grep "Parent Dashboard"

          # Mentor Status
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Mentor dashboard","intent":{"displayName":"MentorStatusIntent"},"parameters":{"mentorId":"MENTOR001"}}}' \
            | grep "Mentor Dashboard"

          # Marketplace
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Show marketplace","intent":{"displayName":"MarketplaceIntent"}}}' \
            | grep "Marketplace Listings"

          # Mentorship
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Show mentors","intent":{"displayName":"MentorshipIntent"}}}' \
            | grep "Mentorship Available"

          # Counseling
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"I need counseling","intent":{"displayName":"CounselingIntent"}}}' \
            | grep "Counseling services"

          # Distress
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"I feel very depressed","intent":{"displayName":"DistressIntent"}}}' \
            | grep "distress"

      - name: Run Sentiment Tests
        run: |
          # Positive Sentiment
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"I am super happy today","intent":{"displayName":"Default Fallback Intent"}}}' \
            | grep "Glad you’re doing well"

          # Negative Sentiment
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"I feel hopeless","intent":{"displayName":"Default Fallback Intent"}}}' \
            | grep "connect you to a counselor"

      - name: Run Fallback Test
        run: |
          curl -s -X POST http://localhost:5000/webhook \
            -H "Content-Type: application/json" \
            -d '{"queryResult":{"queryText":"Blah blah blah","intent":{"displayName":"Default Fallback Intent"}}}' \
            | grep "couldn’t find"
